// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzqpmsbfsinodsdpegct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cXBtc2Jmc2lub2RzZHBlZ2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzExNTgsImV4cCI6MjA3MjMwNzE1OH0.ugm5r1aP4lG3jHd1Gr1aCO4gUyWPyjbTzl6PsTUx3jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});